<a href="https://colab.research.google.com/github/L-Rittmeister/U1_Team/blob/victor/Copy_of_TL_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica #1: Modelo para predicción de lluvia**

*Centro Universitario de Ciencias Exactas e Ingenierías*

*División de Tecnologías para la Integración Ciber-Humana*

*Ingeniería Biomédica*

<br>

*Mtra. Sofía Alejandra Aguilar Valdez*

2 de septiembre de 2022

## **Información del equipo**

```NOMBRES:``` \\
Victor Alvarado Aparicio \\
Dayana Analy Pacheco Bañuelos \\
Leonardo Juàrez Zucco

```CÓDIGOS:``` \\
215767685 \\
217535226 \\
220285869

```LINK REPOSITORIO:``` https://github.com/L-Rittmeister/U1_Team.git



## **Contenido**



1.   Resumen
2.   Marco teórico
3.   Objetivos
4.   Materiales y métodos
5.   Resultados
6.   Discusión
7.   Conclusiones
8.   Referencias



# **1. Resumen**
(100-300 palabras)

En este trabajo se pretendía realizar un modelo de predicción de la lluvia utilizando datos de la estación meteorológica del aeropuerto de Seattle, para este modelo teorizamos utilizar 4 entradas de información para las 4 variables con las que contábamos que eran la probabilidad de precipitación, las temperaturas máxima y mínima y una confirmación si llovió o no con una capa oculta. La metodología utilizada empieza primero con la descargar datos, después la construcción del modelo con las entradas y variables mencionadas antes, además declaramos la función de costo nn.CrossEntropyLoss(), y también un algoritmo de optimización optim.SGD(model.parameters(), lr=0.001), para el ajuste de parámetros de la red, por último el entrenamiento del modelo y la evaluación de este. Sin embargo, en la parte de la evaluación de la red aparentemente se logra hacer que funcione, pero no logramos revisar los resultados.

# **2. Marco teórico**
(300-800 palabras)

# **3. Objetivos**
Objetivo general y objetivos específicos

Objetivo general y objetivos específicos es procesar los datos y crear los objetos e instancias necesarios para poder hacer correr este modelo. Crear un modelo de red neuronal que sea capaz de predecir si llovera o no en Seattle, Washington, USA, utilizando los datos de la estacion meteorologica del aeropuerto de Seattle. Entrenar el modelo con los datos de entrenamiento y probarlo con los datos de prueba. Evaluar el modelo y ver que tan bueno es.

# **4. Materiales y métodos**

## *Materiales*

Describir este conjunto de datos [[1]](https://www.kaggle.com/code/fatmakursun/rain-forecasting-with-artificial-neural-network/data).

## *Métodos*

1. Esquema de metodología
2. Descripción de los métodos y su implementación en código en forma de narrativa.

In [1]:
# Bibliotecas
import pandas as pd
import numpy as np
from numpy import sqrt
from numpy import vstack
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, classification_report
from sklearn.metrics import roc_curve
from tqdm.notebook import trange, tqdm
import time
import torch
from torch import nn
from torch.nn.functional import normalize
from torchvision import datasets, transforms
import torch.utils.data as data
from torch.utils.data import Dataset
import torch.nn.functional as F
from torch import optim
from torch.optim import SGD
from torchvision import datasets, transforms
from torch.utils.data import random_split, DataLoader
from torch.nn.modules.activation import ReLU
from torch.nn.init import kaiming_uniform_
from torch.nn.init import xavier_uniform_
from datetime import datetime


In [2]:
!git version

git version 2.17.1


In [3]:
!git config --global user.email “victor.alvarado7676@alumnos.udg.mx”

In [4]:
!git config --global user.name “L-Rittmeister”

In [5]:
!ls

sample_data


In [6]:
!git clone https://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@github.com/L-Rittmeister/U1_Team.git

Cloning into 'U1_Team'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 89 (delta 46), reused 46 (delta 17), pack-reused 0
Unpacking objects: 100% (89/89), done.


In [7]:
!ls

sample_data  U1_Team


In [8]:
%cd U1_Team/

/content/U1_Team


In [9]:
!pwd

/content/U1_Team


In [10]:
!ls

Copy_of_TL_P1.ipynb  dummy.md  README.md  seattleWeather_1948-2017.csv


In [11]:
!git checkout main

Already on 'main'
Your branch is up to date with 'origin/main'.


In [12]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [13]:
!git pull

Already up to date.


In [14]:
!ls

Copy_of_TL_P1.ipynb  dummy.md  README.md  seattleWeather_1948-2017.csv


In [ ]:
torch.randn(5).cuda()

tensor([ 0.7381, -0.6979, -0.0391,  1.9942,  0.2198], device='cuda:0')

In [68]:
# Train, Val split
data = pd.read_csv('seattleWeather_1948-2017.csv')
data

DATE  PRCP  TMAX  TMIN   RAIN
0      1948-01-01  0.47    51    42   True
1      1948-01-02  0.59    45    36   True
2      1948-01-03  0.42    45    35   True
3      1948-01-04  0.31    45    34   True
4      1948-01-05  0.17    45    32   True
...           ...   ...   ...   ...    ...
25546  2017-12-10  0.00    49    34  False
25547  2017-12-11  0.00    49    29  False
25548  2017-12-12  0.00    46    32  False
25549  2017-12-13  0.00    48    34  False
25550  2017-12-14  0.00    50    36  False

[25551 rows x 5 columns]

In [69]:
# NaN values deletion
data.dropna(inplace=True)
data.reset_index(inplace=True, drop=True)
data

DATE  PRCP  TMAX  TMIN   RAIN
0      1948-01-01  0.47    51    42   True
1      1948-01-02  0.59    45    36   True
2      1948-01-03  0.42    45    35   True
3      1948-01-04  0.31    45    34   True
4      1948-01-05  0.17    45    32   True
...           ...   ...   ...   ...    ...
25543  2017-12-10  0.00    49    34  False
25544  2017-12-11  0.00    49    29  False
25545  2017-12-12  0.00    46    32  False
25546  2017-12-13  0.00    48    34  False
25547  2017-12-14  0.00    50    36  False

[25548 rows x 5 columns]

In [70]:
#Create a n array with the values of PRCP, TMAX, TMIN, and RAIN
data = data[['PRCP', 'TMAX', 'TMIN', 'RAIN']]
data

PRCP  TMAX  TMIN   RAIN
0      0.47    51    42   True
1      0.59    45    36   True
2      0.42    45    35   True
3      0.31    45    34   True
4      0.17    45    32   True
...     ...   ...   ...    ...
25543  0.00    49    34  False
25544  0.00    49    29  False
25545  0.00    46    32  False
25546  0.00    48    34  False
25547  0.00    50    36  False

[25548 rows x 4 columns]

In [71]:
#Eliminate possible void values
data = data[data['PRCP'] != 'T']
data = data[data['TMAX'] != 'T']
data = data[data['TMIN'] != 'T']
data = data[data['RAIN'] != 'T']
data

PRCP  TMAX  TMIN   RAIN
0      0.47    51    42   True
1      0.59    45    36   True
2      0.42    45    35   True
3      0.31    45    34   True
4      0.17    45    32   True
...     ...   ...   ...    ...
25543  0.00    49    34  False
25544  0.00    49    29  False
25545  0.00    46    32  False
25546  0.00    48    34  False
25547  0.00    50    36  False

[25548 rows x 4 columns]

In [72]:
#Convert the values of PRCP, TMAX, TMIN, and RAIN to float
data['PRCP'] = data['PRCP'].astype(float)
data['TMAX'] = data['TMAX'].astype(float)
data['TMIN'] = data['TMIN'].astype(float)
data['RAIN'] = data['RAIN'].astype(float)
data

PRCP  TMAX  TMIN  RAIN
0      0.47  51.0  42.0   1.0
1      0.59  45.0  36.0   1.0
2      0.42  45.0  35.0   1.0
3      0.31  45.0  34.0   1.0
4      0.17  45.0  32.0   1.0
...     ...   ...   ...   ...
25543  0.00  49.0  34.0   0.0
25544  0.00  49.0  29.0   0.0
25545  0.00  46.0  32.0   0.0
25546  0.00  48.0  34.0   0.0
25547  0.00  50.0  36.0   0.0

[25548 rows x 4 columns]

In [73]:
labels = data['RAIN']
labels

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
25543    0.0
25544    0.0
25545    0.0
25546    0.0
25547    0.0
Name: RAIN, Length: 25548, dtype: float64

In [74]:
data = data[['PRCP', 'TMAX', 'TMIN']]
data

PRCP  TMAX  TMIN
0      0.47  51.0  42.0
1      0.59  45.0  36.0
2      0.42  45.0  35.0
3      0.31  45.0  34.0
4      0.17  45.0  32.0
...     ...   ...   ...
25543  0.00  49.0  34.0
25544  0.00  49.0  29.0
25545  0.00  46.0  32.0
25546  0.00  48.0  34.0
25547  0.00  50.0  36.0

[25548 rows x 3 columns]

In [75]:
labeledData = []
for i in range(len(data)):
  labeledData.append((data.values[i],labels.values[i]))

In [97]:
labeledData[0]

(array([ 0.47, 51.  , 42.  ]), 1.0)

In [92]:
bla = np.array(labeledData[:, :]).astype(np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [99]:
bla = bla.astype(float)

PRCP  TMAX  TMIN
0      0.47  51.0  42.0
1      0.59  45.0  36.0
2      0.42  45.0  35.0
3      0.31  45.0  34.0
4      0.17  45.0  32.0
...     ...   ...   ...
25543  0.00  49.0  34.0
25544  0.00  49.0  29.0
25545  0.00  46.0  32.0
25546  0.00  48.0  34.0
25547  0.00  50.0  36.0

[25548 rows x 3 columns]

In [100]:
# Create the tensor
#data = torch.tensor(data.values)
dataTensor = torch.from_numpy(np.array(bla)).float()
dataTensor

tensor([[ 0.4700, 51.0000, 42.0000],
        [ 0.5900, 45.0000, 36.0000],
        [ 0.4200, 45.0000, 35.0000],
        ...,
        [ 0.0000, 46.0000, 32.0000],
        [ 0.0000, 48.0000, 34.0000],
        [ 0.0000, 50.0000, 36.0000]])

In [101]:
# Data split, training and validation dataloaders creation
train_data, val_data = random_split(dataTensor, [20548, 5000])
train_loader = DataLoader(train_data, batch_size = 4, shuffle=True)
val_loader = DataLoader(val_data, batch_size = 4, shuffle=True)

In [102]:
# Definir modelo

class ResNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(4,4)
        self.l2 = nn.Linear(4,4)
        self.l3 = nn.Linear(4,1)
        self.do = nn.Dropout(0.1)

    def forward(self,x):
        h1 = nn.functional.relu(self.l1(x)) # Hidden layer
        h2 = nn.functional.relu(self.l2(h1))
        do = self.do(h2 + h1)
        logits = self.l3(do)
        return logits

model = ResNet().cuda()

RuntimeError: ignored

In [ ]:
# Definir optimizador
params = model.parameters()
optimizer = optim.SGD(params, lr=1e-2)

In [ ]:
# Definir función de costo
loss = nn.CrossEntropyLoss()

In [ ]:
# Ciclos de entrenamiento y validacion
nb_epochs = 5
for epoch in range(nb_epochs):
    losses = list()
    accuracies = list()
    model.train()
    for batch in train_loader:
        x, y = batch

        # x : b x 1 x 4 x 4
        b = x.size(0)
        x = x.view(b, -1).cuda()

        # 1. forward 
        l = model(x.float()) # l: logits

        # 2. evaluación de la función objetivo
        j = loss(l, y.cuda())

        # 3. limpieza de gradientes
        model.zero_grad()

        # 4. Backpropagation: acumular derivadas parciales de la función de costo
        j.backward()

        # 5. retroceder hacia la dirección opuesta del gradiente (aprendizaje)
        optimizer.step()

        losses.append(j.item())
        accuracies.append(y.eq(l.detach().argmax(dim = 1).cpu()).float().mean())

    print(f'Epoch {epoch +1}', end = ', ')
    print(f'Training loss: {torch.tensor(losses).mean():.2f}', end = ', ')
    print(f'Training accuracy: {torch.tensor(accuracies).mean():.2f}')

    losses = list()
    accuracies = list()
    model.eval() 
    for batch in val_loader:
        x, y = batch
        
        # x : b x 1 x 4 x 4
        b = x.size(0)
        x = x.view(b, -1).cuda()

        # 1. forward 
        with torch.no_grad():
             l = model(x.float()) # l: logits

        # 2. evaluación de la función objetivo
        j = loss(l, y.cuda())

        losses.append(j.item())
        accuracies.append(y.eq(l.detach().argmax(dim = 1).cpu()).float().mean())



    print(f'Epoch {epoch +1}', end = ', ')
    print(f'Validation loss: {torch.tensor(losses).mean():.2f}', end = ', ')
    print(f'Validation accuracy: {torch.tensor(accuracies).mean():.2f}')

ValueError: ignored

In [ ]:
batch

tensor([[ 0.0000, 64.0000, 38.0000],
        [ 0.0000, 82.0000, 59.0000],
        [ 0.0000, 81.0000, 52.0000],
        [ 0.4200, 65.0000, 46.0000]], dtype=torch.float64)

# **5. Resultados**
(300-800 palabras, incluir mínimo 2 figuras).

# **6. Discusión**
Underfitting, overfitting, o no y el porqué
Comparación de su metodología con literatura asociada

# **7. Conclusiones**
(100-300 palabras).

En particular Este trabajo demoestró una complejidad y un desafio en la implementacion de redes neuronales en la plataforma pytorch y si bien los resultados no fueron satisfactorios fue una buena experiencia para aprender a utilizar esta plataforma y sus herramientas.

Al finalizar el modelo de predicción de la lluvia no se cumplieron los objetivos tal cual se esperaba, sin embargo fue un reto trabajar con este tipo de ANN en múltiples capas y la red neuronal, además para aterrizar lo aprendido y aprender a usar git hub, me pareció una experiencia bien.

# **8. Referencias**

[1] Pb, V. (2020, February 18). Perceptron. Kaggle. Retrieved June 1, 2022, from https://www.kaggle.com/code/prashfio/perceptron/notebook