<a href="https://colab.research.google.com/github/L-Rittmeister/U1_Team/blob/victor/Copy_of_TL_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica #1: Modelo para predicción de lluvia**

*Centro Universitario de Ciencias Exactas e Ingenierías*

*División de Tecnologías para la Integración Ciber-Humana*

*Ingeniería Biomédica*

<br>

*Mtra. Sofía Alejandra Aguilar Valdez*

2 de septiembre de 2022

## **Información del equipo**

```NOMBRES:``` \\
Victor Alvarado Aparicio \\
Dayana Analy Pacheco Bañuelos \\
Leonardo Juàrez Zucco

```CÓDIGOS:``` \\
215767685 \\
217535226 \\
220285869

```LINK REPOSITORIO:``` https://github.com/L-Rittmeister/U1_Team.git



## **Contenido**



1.   Resumen
2.   Marco teórico
3.   Objetivos
4.   Materiales y métodos
5.   Resultados
6.   Discusión
7.   Conclusiones
8.   Referencias



# **1. Resumen**
(100-300 palabras)

# **2. Marco teórico**
(300-800 palabras)

# **3. Objetivos**
Objetivo general y objetivos específicos

# **4. Materiales y métodos**

## *Materiales*

Describir este conjunto de datos [[1]](https://www.kaggle.com/code/fatmakursun/rain-forecasting-with-artificial-neural-network/data).

## *Métodos*

1. Esquema de metodología
2. Descripción de los métodos y su implementación en código en forma de narrativa.

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [31]:
# Bibliotecas
import pandas as pd
import numpy as np
from numpy import sqrt
from numpy import vstack
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, classification_report
from sklearn.metrics import roc_curve
from tqdm.notebook import trange, tqdm
import time
import torch
from torch import nn
from torch.nn.functional import normalize
from torchvision import datasets, transforms
import torch.utils.data as data
from torch.utils.data import Dataset
import torch.nn.functional as F
from torch import optim
from torch.optim import SGD
from torchvision import datasets, transforms
from torch.utils.data import random_split, DataLoader
from torch.nn.modules.activation import ReLU
from torch.nn.init import kaiming_uniform_
from torch.nn.init import xavier_uniform_
from datetime import datetime


In [32]:
!git version

git version 2.17.1


In [33]:
!git config --global user.email “victor.alvarado7676@alumnos.udg.mx”

In [34]:
!git config --global user.name “L-Rittmeister”

In [35]:
!ls

Copy_of_TL_P1.ipynb  dummy.md  README.md  seattleWeather_1948-2017.csv


In [36]:
!git clone https://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@github.com/L-Rittmeister/U1_Team.git

Cloning into 'U1_Team'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 48 (delta 20), reused 28 (delta 9), pack-reused 0
Unpacking objects: 100% (48/48), done.


In [37]:
!ls

Copy_of_TL_P1.ipynb  dummy.md  README.md  seattleWeather_1948-2017.csv	U1_Team


In [38]:
%cd U1_Team/

/content/U1_Team/U1_Team


In [39]:
!pwd

/content/U1_Team/U1_Team


In [40]:
!ls

Copy_of_TL_P1.ipynb  dummy.md  README.md  seattleWeather_1948-2017.csv


In [78]:
!git checkout victor

Branch 'victor' set up to track remote branch 'victor' from 'origin'.
Switched to a new branch 'victor'


In [79]:
!git status

On branch victor
Your branch is up to date with 'origin/victor'.

nothing to commit, working tree clean


In [43]:
!git pull

Already up to date.


In [44]:
!ls

Copy_of_TL_P1.ipynb  dummy.md  README.md  seattleWeather_1948-2017.csv


In [45]:
torch.randn(5).cuda()

tensor([ 1.4075, -0.2169, -0.7548, -0.6048,  1.0726], device='cuda:0')

In [46]:
# Train, Val split
data = pd.read_csv('seattleWeather_1948-2017.csv')
data

DATE  PRCP  TMAX  TMIN   RAIN
0      1948-01-01  0.47    51    42   True
1      1948-01-02  0.59    45    36   True
2      1948-01-03  0.42    45    35   True
3      1948-01-04  0.31    45    34   True
4      1948-01-05  0.17    45    32   True
...           ...   ...   ...   ...    ...
25546  2017-12-10  0.00    49    34  False
25547  2017-12-11  0.00    49    29  False
25548  2017-12-12  0.00    46    32  False
25549  2017-12-13  0.00    48    34  False
25550  2017-12-14  0.00    50    36  False

[25551 rows x 5 columns]

In [47]:
# NaN values deletion
data.dropna(inplace=True)
data.reset_index(inplace=True, drop=True)
data

DATE  PRCP  TMAX  TMIN   RAIN
0      1948-01-01  0.47    51    42   True
1      1948-01-02  0.59    45    36   True
2      1948-01-03  0.42    45    35   True
3      1948-01-04  0.31    45    34   True
4      1948-01-05  0.17    45    32   True
...           ...   ...   ...   ...    ...
25543  2017-12-10  0.00    49    34  False
25544  2017-12-11  0.00    49    29  False
25545  2017-12-12  0.00    46    32  False
25546  2017-12-13  0.00    48    34  False
25547  2017-12-14  0.00    50    36  False

[25548 rows x 5 columns]

In [48]:
#Create a n array with the values of PRCP, TMAX, TMIN, and RAIN
data = data[['PRCP', 'TMAX', 'TMIN', 'RAIN']]
data

PRCP  TMAX  TMIN   RAIN
0      0.47    51    42   True
1      0.59    45    36   True
2      0.42    45    35   True
3      0.31    45    34   True
4      0.17    45    32   True
...     ...   ...   ...    ...
25543  0.00    49    34  False
25544  0.00    49    29  False
25545  0.00    46    32  False
25546  0.00    48    34  False
25547  0.00    50    36  False

[25548 rows x 4 columns]

In [49]:
#Eliminate possible void values
data = data[data['PRCP'] != 'T']
data = data[data['TMAX'] != 'T']
data = data[data['TMIN'] != 'T']
data = data[data['RAIN'] != 'T']
data

PRCP  TMAX  TMIN   RAIN
0      0.47    51    42   True
1      0.59    45    36   True
2      0.42    45    35   True
3      0.31    45    34   True
4      0.17    45    32   True
...     ...   ...   ...    ...
25543  0.00    49    34  False
25544  0.00    49    29  False
25545  0.00    46    32  False
25546  0.00    48    34  False
25547  0.00    50    36  False

[25548 rows x 4 columns]

In [50]:
#Convert the values of PRCP, TMAX, TMIN, and RAIN to float
data['PRCP'] = data['PRCP'].astype(float)
data['TMAX'] = data['TMAX'].astype(float)
data['TMIN'] = data['TMIN'].astype(float)
data['RAIN'] = data['RAIN'].astype(float)
data

PRCP  TMAX  TMIN  RAIN
0      0.47  51.0  42.0   1.0
1      0.59  45.0  36.0   1.0
2      0.42  45.0  35.0   1.0
3      0.31  45.0  34.0   1.0
4      0.17  45.0  32.0   1.0
...     ...   ...   ...   ...
25543  0.00  49.0  34.0   0.0
25544  0.00  49.0  29.0   0.0
25545  0.00  46.0  32.0   0.0
25546  0.00  48.0  34.0   0.0
25547  0.00  50.0  36.0   0.0

[25548 rows x 4 columns]

In [51]:
# Create the tensor
data = torch.tensor(data.values)
data[1]

tensor([ 0.5900, 45.0000, 36.0000,  1.0000], dtype=torch.float64)

In [72]:
# Data split, training and validation dataloaders creation
train_data, val_data = random_split(data, [20548, 5000])
train_loader = DataLoader(train_data, batch_size = 4)
val_loader = DataLoader(val_data, batch_size = 4)
y = [0,0,0,0]
y = torch.tensor(y)

In [73]:
y

tensor([0, 0, 0, 0])

In [74]:
# Definir modelo

class ResNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(4,4)
        self.l2 = nn.Linear(4,4)
        self.l3 = nn.Linear(4,1)
        self.do = nn.Dropout(0.1)

    def forward(self,x):
        h1 = nn.functional.relu(self.l1(x)) # Hidden layer
        h2 = nn.functional.relu(self.l2(h1))
        do = self.do(h2 + h1)
        logits = self.l3(do)
        return logits

model = ResNet().cuda()

In [75]:
# Definir optimizador
params = model.parameters()
optimizer = optim.SGD(params, lr=1e-2)

In [76]:
# Definir función de costo
loss = nn.CrossEntropyLoss()

In [80]:
# Ciclos de entrenamiento y validacion
nb_epochs = 5
for epoch in range(nb_epochs):
    losses = list()
    accuracies = list()
    model.train()
    for batch in train_loader:
        x = batch

        # x : b x 1 x 4 x 4
        b = x.size(0)
        x = x.view(b, -1).cuda()

        # 1. forward 
        l = model(x.float()) # l: logits

        # 2. evaluación de la función objetivo
        j = loss(l, y.cuda())

        # 3. limpieza de gradientes
        model.zero_grad()

        # 4. Backpropagation: acumular derivadas parciales de la función de costo
        j.backward()

        # 5. retroceder hacia la dirección opuesta del gradiente (aprendizaje)
        optimizer.step()

        losses.append(j.item())
        accuracies.append(y.eq(l.detach().argmax(dim = 1).cpu()).float().mean())

    print(f'Epoch {epoch +1}', end = ', ')
    print(f'Training loss: {torch.tensor(losses).mean():.2f}', end = ', ')
    print(f'Training accuracy: {torch.tensor(accuracies).mean():.2f}')

    losses = list()
    accuracies = list()
    model.eval() 
    for batch in val_loader:
        x = batch
        
        # x : b x 1 x 4 x 4
        b = x.size(0)
        x = x.view(b, -1).cuda()

        # 1. forward 
        with torch.no_grad():
             l = model(x.float()) # l: logits

        # 2. evaluación de la función objetivo
        j = loss(l, y.cuda())

        losses.append(j.item())
        accuracies.append(y.eq(l.detach().argmax(dim = 1).cpu()).float().mean())



    print(f'Epoch {epoch +1}', end = ', ')
    print(f'Validation loss: {torch.tensor(losses).mean():.2f}', end = ', ')
    print(f'Validation accuracy: {torch.tensor(accuracies).mean():.2f}')

Epoch 1, Training loss: 0.00, Training accuracy: 1.00
Epoch 1, Validation loss: 0.00, Validation accuracy: 1.00
Epoch 2, Training loss: 0.00, Training accuracy: 1.00
Epoch 2, Validation loss: 0.00, Validation accuracy: 1.00
Epoch 3, Training loss: 0.00, Training accuracy: 1.00
Epoch 3, Validation loss: 0.00, Validation accuracy: 1.00
Epoch 4, Training loss: 0.00, Training accuracy: 1.00
Epoch 4, Validation loss: 0.00, Validation accuracy: 1.00
Epoch 5, Training loss: 0.00, Training accuracy: 1.00
Epoch 5, Validation loss: 0.00, Validation accuracy: 1.00


tensor([[0.0000e+00, 6.6000e+01, 5.2000e+01, 0.0000e+00],
        [1.0000e-02, 5.4000e+01, 4.9000e+01, 1.0000e+00],
        [0.0000e+00, 7.4000e+01, 5.1000e+01, 0.0000e+00],
        [7.3000e-01, 6.3000e+01, 5.1000e+01, 1.0000e+00],
        [0.0000e+00, 6.1000e+01, 4.0000e+01, 0.0000e+00],
        [0.0000e+00, 6.2000e+01, 4.7000e+01, 0.0000e+00]], device='cuda:0',
       dtype=torch.float64)

# **5. Resultados**
(300-800 palabras, incluir mínimo 2 figuras).

# **6. Discusión**
Underfitting, overfitting, o no y el porqué
Comparación de su metodología con literatura asociada

# **7. Conclusiones**
(100-300 palabras).

# **8. Referencias**

[1] Pb, V. (2020, February 18). Perceptron. Kaggle. Retrieved June 1, 2022, from https://www.kaggle.com/code/prashfio/perceptron/notebook